++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[NM:914del] [X:Ecu DELCO ] [F:44][A:0][CM:00001000]
2 RPM        /* Engine speed ; 1 rpm */
1 VOLEF      /* Volumetric efficecy */
1 STPS       /* Scaled TPS ; 100/256 % */
1 PDTPS      /* Positive delta TPS */
2 BPWTH      /* Base pulse width ; 5 uS */
1 AEPWTH     /* AE pulse width ; 20 uS */
1 DEPWTH     /* DE base pulse width 20 uS */
2 MAPAD      /* Map A/D ; 1 cnt */
1 CS50A      /* Calibratable spare 50 A */
1 CS50B      /* Calibratable spare 50 B */
1 CS50C      /* Calibratable spare 50 C */
1 CS50D      /* Calibratable spare 50 D */
1 FUELPR     /* Fuel press. ; 1 psi */
1 INJAPW     /* Injector A pulse width ; 80 uS */
1 INJBPW     /* Injector B pulse width; 80 uS */
1 SPRKAD     /* Spark advance ; 0.25 deg */
1 LAMLFT     /* Lambda left ; 0.005 */
1 LAMRGT     /* Lambda rifht ; 0.005 */
1 CS100A     /* Calibratable spare 100 A */
1 CS100B     /* Calibratable spare 100 B */
1 OILPR      /* Oli press. ; 1 psi */
1 BATVOL     /* Battery voltage ; 0.1 v */
1 MAINAT     /* Mainfold air temp ; 0.5 deg C */
1 THROTP     /* Throttle position ; 1 cnt */
1 MAINAP     /* Mainfold air press. ; 0.1 inhg */
1 CS200B     /* Calibratable spare 200 B */
2 FUEUSD     /* Fuel used ; 0.05 gal */
1 OILTMP     /* Oil temperature ; 0.5 deg C */
1 COOLT      /* Coolant temp. ; 0.5 deg C */
1 GBOXT      /* Gear box temp ; 0.05 deg C */
1 ECMTMP     /* ECM temp. ; 0.5 deg C */
1 DIAGAD     /* Diagnostic A/D ; 1 cnt */
1 FUELTR     /* Fuel trim ;  0.5 %  */
1 IDLETR     /* Idle trim ; 0.005 */
1 CALPT      /* Cal pointer in ECM */
1 C1000A     /* Calibratable spare 1000 A */
2 SPRKRL     /* Spark rev limiter ; 25 rpm */
2 RRHC       /* Ref run high counter (crank trig err.) */
2 RRLC       /* ref run low counter ( crank trig err.) */
1 C1000C     /* Calibratable spare 1000 C */
1 RESER1     /* Reserved Marelli 1 */
1 RESER2     /* Reserved Marelli 2 */
1 RESER3     /* Reserved Marelli 3 */
2 Reser4     /* Reserved Marelli 4 */	
