++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[NM:930/3] [X:Das3 - Internal Channels] [F:8] [A:0][CM:00000100]
2 ----     /*         */
2 TIME     /* Current Time second hundredth part */
2 LAPTIM   /* Current Laptime second hundredth part */
2 LAP      /* Current Lap */
2 RUN      /* Acquire Session */
2 CSEC     /* Current second Time */
2 MFULL    /* Filled memory 1/1000 parts of memory */
2 SPACE    /* DAS3 Lap distance counter (Read Impulse SPEED Ch) */

