++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[NM:930/3] [X:Das3 - Analog Input] [A:0] [F:8] [LM:1] [CM:10000000]
2 AIN1          /* MT930/3 Analog Input 1 */
2 AIN2          /* MT930/3 Analog Input 2 */
2 AIN3          /* MT930/3 Analog Input 3 */
2 AIN4          /* MT930/3 Analog Input 4 */
2 AIN5          /* MT930/3 Analog Input 5 */
2 AIN6          /* MT930/3 Analog Input 6 */
2 AIN7          /* MT930/3 Analog Input 7 */
2 AIN8          /* MT930/3 Analog Input 8 */
