++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[NM:DUC_01] [X:Ecu DUC_01 ] [F:40][A:0][CM:00001000]
2 RPM        /* N/E  */
1 ADV        /* spark advance ; 0.0=0.0 , 100.0=25.0 */
1 TPOS       /* Throttle position ; 0=0 , 255.0=90.00 */
2 PARIA      /* air pressure ; NE */
2 TINJB      /* base inj time ; NE */
2 TINJH      /* high bank inj time ; NE*/
2 TINJL      /* low bank inj time ; NE*/
2 DFARFP     /* tpos rate of chg pos ; NE */
2 DFARFN     /* tpos rate of chg neg ; NE */
2 PERCV      /* NE */
1 CUTGEA     /* gear cut ; NE */
1 STATGE     /* NE */
2 LAM_H      /* lambda horiz ; NE */
2 LAM_V      /* lambda vert ; NE */
2 SMOT0      /*-----------*/
2 SMOT1      /*-----------*/
2 SMOT2      /*-----------*/
2 SMOT3      /*-----------*/
2 SMOT4      /*-----------*/
2 SMOT5      /*-----------*/
2 SMOT6      /*-----------*/
2 SMOT7      /*-----------*/
1 PHASE      /* inj phase ; 0=0 , 255=720 */
1 PHASEL     /* inj phase low ; 0=0 , 255=720 */
1 GEAR       /*-----------*/
1 GEARC      /*-----------*/
2 GEARP      /*-----------*/
2 SPEED      /*-----------*/
2 LIVELL     /*-----------*/
2 GEARTI     /* NE */
1 BATT       /* battery volts ; 0=0 , 255.0=18.0 */
1 AIRT       /* air temp ; 0= -30 , 255=150 */
1 WATERT     /* water temp ; 0= -30 , 255=150 */
1 FUELT      /*-----------*/
1 RIPINJ     /*-----------*/
1 MANETT     /* NE */
2 DIAG       /* NE */
2 AUXFLG     /*-----------*/
1 XFLG1      /*-----------*/
1 XFLG2      /*-----------*/
