+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[NM:EUROC_2] [X:EUROC_2 DIRECT MT940] [F:12] [A:0] [CM:00001000]
2 RPM        /* ENGINE SPEED */
2 TPS        /* T POS 0-0 255-90 */
2 BATT       /* BATT 0-0 255-18 */
2 WAT_L      /* WATER 0-0 180-150 */
2 WAT_R      /* WATER RIGHT 0=0  180=150 */
2 AIRT       /* AIR TEMP 0=0  180=150 */
2 FUELP      /* FUEL PRESS 0-0 1000-1 1dp */
2 AIRP       /* air press mbar N/E */
2 BAROP      /* baro press N/E */
2 DIAG       /*  N/E */
2 ECU11      /* --- */
2 ECU12      /* --- */
