+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[NM:941] [X:uDas - Input Capture] [A:0] [F:6] [RM:2] [CM:00100000]
2 IC1          /*MT941 Input Capture 1 (Speed 1)*/
2 IC2          /*MT941 Input Capture 2 (Rpm)*/
2 IC3          /*MT941 Input Capture 3 (Speed 2)*/
2 CNT1         /*MT941 Counter Input Capture 1*/
2 CNT2         /*MT941 Counter Input Capture 2*/
2 CNT3         /*MT941 Counter Input Capture 3*/
