+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[NM:MR3 MT940] [X:MR3 MT940] [F:12] [A:0] [CM:00001000]
2 RPM           /* MT940 Analog Input 1 */
1 TPOS          /* MT940 Analog Input 2 */
1 BATT          /* MT940 Analog Input 3 */
2 OILP          /* MT940 Analog Input 4 */
1 WATER         /*            */
1 WAT_R         /*            */
1 AIRT          /* MT940 Vbat Input */
2 FUELP         /* MT940 Lap Input */
2 AIRP          /* MT940 Rpm Input */
2 BARO          /* MT940 Speed Input */
1 DIAG          /* MT940 Max Speed Input */
4 LEVEL         /* MT940 Min Speed Input */
