+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[NM:300] [X:DashBoard 1 window with pointer] [F:11] [A:48] [RM:0] [CM:00001000]
2 DBAIN1        /* MT300 Elaborated Analog Input 1 */
2 DBAIN2        /* MT300 Elaborated Analog Input 2 */
2 DBAIN3        /* MT300 Elaborated Analog Input 3 */
2 DBAIN4        /* MT300 Elaborated Analog Input 4 */
2 DBAIN5        /* MT300 Elaborated Analog Input 5 */
2 DBAIN6        /* MT300 Elaborated Analog Input 6 */
2 DBVBAT        /* MT300 Vbat Input */
2 DBLAP         /* MT300 Lap Input */
2 DBRPM         /* MT300 Rpm Input */
2 DBSPEE        /* MT300 Speed Input */
2 DBCNTS        /* MT300 Counter Speed Input capture */
