+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[NM:847] [X:16 Differential Analog Input] [F:16] [LM:1] [A:192] [CM:00001000]
2 ADIN1      /* Differential analog input 1 */
2 ADIN2      /* Differential analog input 2 */
2 ADIN3      /* Differential analog input 3 */
2 ADIN4      /* Differential analog input 4 */
2 ADIN5      /* Differential analog input 5 */
2 ADIN6      /* Differential analog input 6 */
2 ADIN7      /* Differential analog input 7 */
2 ADIN8      /* Differential analog input 8 */
2 ADIN9      /* Differential analog input 9 */
2 ADIN10     /* Differential analog input 10 */
2 ADIN11     /* Differential analog input 11 */
2 ADIN12     /* Differential analog input 12 */
2 ADIN13     /* Differential analog input 13 */
2 ADIN14     /* Differential analog input 14 */
2 ADIN15     /* Differential analog input 15 */
2 ADIN16     /* Differential analog input 16 */
