+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[NM:917] [X:3 Window DashBoard] [F:8] [A:48] [RM:0] [CM:00001000]
2 DBAIN1        /* MT917 Analog Input 1 */
2 DBAIN2        /* MT917 Analog Input 2 */
2 DBAIN3        /* MT917 Analog Input 3 */
2 DBAIN4        /* MT917 Analog Input 4 */
2 DBVBAT        /* MT917 Vbat Input */
2 DBRPM         /* MT917 Rpm Input */
2 DBTIME        /* MT917 Time Counter */
2 DBSPEE        /* MT917 Speed Input */
