+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[NM:924/B] [X:4 Input Capture] [A:92] [F:8] [RM:0] [CM:00001000]
2 IC1       /*MT924/B Input Capture 1 */
2 IC2       /*MT924/B Input Capture 2 */
2 IC3       /*MT924/B Input Capture 3 */
2 IC4       /*MT924/B Input Capture 4 */
2 AVSP      /*MT924/B Average SPEED CH1-CH2 */
2 CNT1      /*MT924/B Counter Input Capture 1 */
2 CNT2      /*MT924/B Counter Input Capture 2 */
2 AVCNT     /*MT924/B Avarage Counter Input Capture 1-2 */
