++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[NM:931/C] [X:2 Tck + 5 Analog + 2 IC Inputs] [A:128] [F:14] [LM:1] [RM:0] [CM:00001000]
2 ----     /*  */
2 ----     /*  */
2 AIN2     /* Analog input 2 */
2 AIN3     /* Analog input 3 */
2 AIN4     /* Analog input 4 */
2 AIN5     /* Analog input 5 */
2 AIN6     /* Analog input 6 */
2 ----     /*  */
2 IC1      /* Input Capture 1 */
2 IC2      /* Input Capture 2 */
2 CNT1     /* Counter Input Capture 1 */
2 ----
2 TCK0     /* Tck input 0 */
2 TCK1     /* Tck input 1 */
