+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[NM:934] [X:16 Analog Single Ended Inputs] [F:16] [LM:4] [A:192] [CM:00001000]
2 AIN1     /* Analog input 1 */
2 AIN2     /* Analog input 2 */
2 AIN3     /* Analog input 3 */
2 AIN4     /* Analog input 4 */
2 AIN5     /* Analog input 5 */
2 AIN6     /* Analog input 6 */
2 AIN7     /* Analog input 7 */
2 AIN8     /* Analog input 8 */
2 AIN9     /* Analog input 9 */
2 AIN10    /* Analog input 10 */
2 AIN11    /* Analog input 11 */
2 AIN12    /* Analog input 12 */
2 AIN13    /* Analog input 13 */
2 AIN14    /* Analog input 14 */
2 AIN15    /* Analog input 15 */
2 AIN16    /* Analog input 16 */
