++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[NM:931/B] [X:2 Diff + 6 Analog + 2 IC Inputs] [A:128] [F:11] [LM:1] [RM:0] [CM:00001000]
2 ADIN0    /* Differential Analog input 0 */
2 ADIN1    /* Differential Analog input 1 */
2 AIN2     /* Analog input 2 */
2 AIN3     /* Analog input 3 */
2 AIN4     /* Analog input 4 */
2 AIN5     /* Analog input 5 */
2 AIN6     /* Analog input 6 */
2 AIN7     /* Analog input 7 */
2 IC1      /* Input Capture 1 */
2 IC2      /* Input Capture 2 */
2 CNT1     /* Counter Input Capture 1 */
