+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[NM:940] [X:5 Window DashBoard] [F:12] [A:48] [CM:00001000]
2 DBAIN1        /* MT940 Analog Input 1 */
2 DBAIN2        /* MT940 Analog Input 2 */
2 DBAIN3        /* MT940 Analog Input 3 */
2 DBAIN4        /* MT940 Analog Input 4 */
2 ----          /*            */
2 ----          /*            */
2 DBVBAT        /* MT940 Vbat Input */
2 DBLAP         /* MT940 Lap Input */
2 DBRPM         /* MT940 Rpm Input */
2 DBSPEE        /* MT940 Speed Input */
2 MAXSPE        /* MT940 Max Speed Input */
2 MINSPE        /* MT940 Min Speed Input */
